ALTER TABLE CODAF_CERTIFICADOS 
ADD COLUMN IF NOT EXISTS codaf_lista_presenca_id int8 NOT NULL;
ALTER TABLE CODAF_CERTIFICADOS 
ADD CONSTRAINT codaf_certificado_codaf_lista_presenca_id_fk 
FOREIGN KEY (codaf_lista_presenca_id) REFERENCES CODAF_LISTA_PRESENCA;
ALTER TABLE COORDENADORIA
ALTER COLUMN nome TYPE varchar(300),
ALTER COLUMN sigla TYPE varchar(50);