-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE codaf_declaracoes (
	id int8 NOT NULL,
	codigo_declaracao int8 NOT NULL,
	codaf_curso_nao_homologado_inscricao_id int8 NULL,
	proposta_regente_turma_id int8 NULL,
	tipo_participacao int4 NOT NULL,
	data_emissao timestamp NOT NULL,
	html_content_snapshot text NOT NULL,
	metadados_json jsonb NULL,
	criado_em timestamp NOT NULL,
	criado_por varchar(200) NULL,
	alterado_em timestamp NULL,
	alterado_por varchar(200) NULL,
	criado_login varchar(200) NULL,
	alterado_login varchar(200) NULL,
	excluido bool NOT NULL,
	status_processamento int4 NOT NULL,
	chave_objeto_armazenamento varchar(255) NULL,
	erro_processamento text NULL,
	tentativas_processamento int4 NOT NULL,
	codaf_curso_nao_homologado_id int8 NULL
);