-- DDL generated by DBeaver
-- WARNING: It may differ from actual native database DDL
CREATE TABLE IF NOT EXISTS codaf_declaracoes (
    id int8 NOT NULL GENERATED ALWAYS AS IDENTITY(NO MINVALUE NO MAXVALUE NO CYCLE),
	codigo_declaracao int8 NOT NULL,
	codaf_curso_nao_homologado_inscricao_id int8 NULL,
	proposta_regente_turma_id int8 NULL,
	tipo_participacao int4 NOT NULL,
	data_emissao timestamp NOT NULL,
	html_content_snapshot text NOT NULL,
	metadados_json jsonb NULL,
	criado_em timestamp NOT NULL,
	criado_por varchar(200) NULL,
	alterado_em timestamp NULL,
	alterado_por varchar(200) NULL,
	criado_login varchar(200) NULL,
	alterado_login varchar(200) NULL,
	excluido bool NOT NULL,
	status_processamento int4 NOT NULL,
	chave_objeto_armazenamento varchar(255) NULL,
	erro_processamento text NULL,
	tentativas_processamento int4 NOT NULL,
	codaf_curso_nao_homologado_id int8 NULL,

	CONSTRAINT codaf_declaracoes_pk PRIMARY KEY (id),
    CONSTRAINT codaf_declaracao_ccnh_insc_id_fk FOREIGN KEY (codaf_curso_nao_homologado_inscricao_id) REFERENCES codaf_curso_nao_homologado_inscricao(id),
    CONSTRAINT codaf_declaracao_ccnh_id_fk FOREIGN KEY (codaf_curso_nao_homologado_id) REFERENCES codaf_curso_nao_homologado(id)
);

